services:
  db:
    image: mysql:5.7
    container_name: laravelinas_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    volumes:
      - laravelinas_db_data:/var/lib/mysql

  wordpress:
    image: wordpress:php8.2-apache
    container_name: laravelinas_wp
    depends_on:
      - db
    ports:
      - "8090:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    volumes:
      - ./html/wordpress-local:/var/www/html
      - ./php/html/wordpress/wp-content/themes/Laravelinas:/var/www/html/wp-content/themes/Laravelinas

volumes:
  laravelinas_db_data: